### PR TITLE
All working and tracked on NPM

### PR DESCRIPTION
**Pull request by MylesBorins**
Just googled node osc and your github repository is the first item to come up.  This code is far different from what you originally wrote... but it works :D

It is currently an npm package and can be installed via
npm install node-osc

### CODE REVIEW

**Comment by termie** [comment]
wow, somehow i missed all the updates on this stuff, are you interested in being the maintainer for this project?

**Comment by MylesBorins** [comment]
@termie 

Sure (regarding maintaining the project), is there anything more to do in the regard?

**Comment by termie** [comment]
nope, i think i just have to transfer which branch is the master to you and change the description on mine to deprecated :) glad you got use out of the library

**Comment by MylesBorins** [comment]
Cool... I guess just let me know if there is anything I need to do on my end.

Side bar, and possibly totally inappropriate... but I'm a grad student in the bay area looking for summer work / internships.  Noticed you were living in SF.  Do you perhaps have any leads for such opportunities? Companies dealing with music technologies are a plus.

**Comment by termie** [comment]
rackspace, where i used to work, has a pretty decent intern program, i can hook you up there but they don't do anything musicky.

re ownership, there are two ways to do it, i can just put up big DEPRECATED signs on my project, or you can delete yours and i transfer ownership of mine to you, the deprecated is probably easiest, thoughts?

**Comment by MylesBorins** [comment]
My cv is on here at TheAlphaNerd/curriculum_vitae if you want to submit that for me that would be awesome!

I'm thinking DEPRECATED is probably an easier way to go about things.

**Pull request merged**
